final doctors = [
  {
    "id": 1,
    "image": "https://pngimg.com/d/doctor_PNG16002.png",
    "name": "Layla Hassan",
    "specialty": "Cardiology",
    "start_hour": "9:00",
    "end_hour": "1:00",
    "rate": 4.8,
    "experience": 15,
    "treatments": 230,
    "bio":
        "Dr. Layla Hassan brings years of expertise in cardiovascular care. She is known for her thorough diagnosis and patient-first mindset.",
    "qualifications": [
      "Medical Degree (MBBS)",
      "Residency in Internal Medicine",
      "Fellowship in Cardiology",
      "Board Certified in Cardiology",
      "Advanced ECG Interpretation",
    ],
  },
  {
    "id": 2,
    "image": "https://pngimg.com/d/doctor_PNG15957.png",
    "name": "Samer Baker",
    "specialty": "Cardiology",
    "start_hour": "2:00",
    "end_hour": "6:00",
    "rate": 3.7,
    "experience": 20,
    "treatments": 530,
    "bio":
        "Dr. Samer Baker is an experienced cardiologist dedicated to diagnosing and treating heart conditions with a patient-first approach.",
    "qualifications": [
      "Doctor of Medicine (MD)",
      "Board Certified Cardiologist",
      "Advanced Cardiac Life Support (ACLS) Certification",
      "Experience with Diagnostic Tools",
      "Strong Background in Preventive Cardiology and Patient Education",
    ],
  },
  {
    "id": 3,
    "image": "https://pngimg.com/d/doctor_PNG15959.png",
    "name": "Fares Al Midany",
    "specialty": "Neurology",
    "start_hour": "9:00",
    "end_hour": "1:00",
    "rate": 4.5,
    "experience": 19,
    "treatments": 150,
    "bio":
        "Dr. Fares Al Midany is a caring and experienced physician. He combines modern medicine with a warm approach. Always attentive, he listens and understands your needs.",
    "qualifications": [
      "Medical Degree (MBBS or MD)",
      "Residency in Neurology",
      "Board Certification in Neurology",
      "Strong Diagnostic Skills",
      "Subspecialty Training (e.g., Stroke, Epilepsy)",
    ],
  },
  {
    "id": 4,
    "image": "https://pngimg.com/d/doctor_PNG16020.png",
    "name": "Sara Eid",
    "specialty": "Neurology",
    "start_hour": "2:00",
    "end_hour": "6:00",
    "rate": 2.5,
    "experience": 10,
    "treatments": 196,
    "bio":
        "Dr. Sara Eid is a skilled neurologist specializing in diagnosing and managing disorders of the brain, spine, and nervous system.",
    "qualifications": [
      "Doctor of Medicine (MD)",
      "Board Certified in Neurology",
      "Extensive experience in treating epilepsy",
      "Proficient in EEG, MRI, and other neurological diagnostic tools",
      "Strong commitment to continuous medical education and research",
    ],
  },
  {
    "id": 5,
    "image": "https://pngimg.com/d/doctor_PNG15992.png",
    "name": "Omar Khaled",
    "specialty": "Pediatrics",
    "start_hour": "9:00",
    "end_hour": "1:00",
    "rate": 4.7,
    "experience": 10,
    "treatments": 180,
    "bio":
        "Dr. Omar Khaled has a gentle and engaging approach to child healthcare. He ensures children feel safe while receiving quality medical care.",
    "qualifications": [
      "Medical Degree (MD)",
      "Residency in Pediatrics",
      "Board Certified Pediatrician",
      "Child Development Knowledge",
      "Emergency Pediatric Training",
    ],
  },
  {
    "id": 6,
    "image": "https://pngimg.com/d/doctor_PNG16012.png",
    "name": "Rand Skaf",
    "specialty": "Pediatrics",
    "start_hour": "2:00",
    "end_hour": "6:00",
    "rate": 4.2,
    "experience": 20,
    "treatments": 380,
    "bio":
        "Dr. Rand Skaf is a caring pediatrician dedicated to the health and well-being of children from infancy through adolescence.",
    "qualifications": [
      "Doctor of Medicine (MD) with a focus in Pediatrics",
      "Board Certified Pediatrician",
      "Skilled in childhood growth and development care",
      "Experienced in treating common and chronic pediatric illnesses",
      "Strong communication with both children and parents",
    ],
  },
  {
    "id": 7,
    "image": "https://pngimg.com/d/doctor_PNG16014.png",
    "name": "Maya Al Qassem",
    "specialty": "Dermatology",
    "start_hour": "9:00",
    "end_hour": "1:00",
    "rate": 4.9,
    "experience": 12,
    "treatments": 270,
    "bio":
        "Dr. Maya Al Qassem is passionate about skincare and dermatological health. Her personalized treatment plans make her a favorite among patients.",
    "qualifications": [
      "Medical Degree (MBBS)",
      "Dermatology Residency",
      "Laser Therapy Certification",
      "Cosmetic Dermatology Training",
      "Board Certified in Dermatology",
    ],
  },
  {
    "id": 8,
    "image": "https://pngimg.com/d/doctor_PNG16041.png",
    "name": "Yahya Rajab",
    "specialty": "Dermatology",
    "start_hour": "2:00",
    "end_hour": "6:00",
    "rate": 5,
    "experience": 32,
    "treatments": 210,
    "bio":
        "Dr. Yahya Rajab is a dedicated dermatologist with expertise in diagnosing and treating skin, hair, and nail conditions.",
    "qualifications": [
      "Doctor of Medicine (MD) specialized in Dermatology",
      "Board Certified Dermatologist",
      "Skilled in medical, surgical, and cosmetic dermatology",
      "Experienced in treating acne, eczema, psoriasis, and skin cancers",
      "Proficient in dermatological procedures like biopsies",
    ],
  },
  {
    "id": 9,
    "image": "https://pngimg.com/d/doctor_PNG16007.png",
    "name": "Hussein Mansour",
    "specialty": "Oncology",
    "start_hour": "9:00",
    "end_hour": "1:00",
    "rate": 4.6,
    "experience": 17,
    "treatments": 320,
    "bio":
        "Dr. Hussein Mansour specializes in bone and joint care. His surgical precision and rehab knowledge have helped hundreds recover mobility.",
    "qualifications": [
      "MBBS Degree",
      "Orthopedic Surgery Residency",
      "Fellowship in Joint Replacement",
      "Trauma Management Certification",
      "Board Certified Orthopedic Surgeon",
    ],
  },
  {
    "id": 10,
    "image": "https://pngimg.com/d/doctor_PNG15979.png",
    "name": "Esam Rehawe",
    "specialty": "Oncology",
    "start_hour": "2:00",
    "end_hour": "6:00",
    "rate": 2.6,
    "experience": 7,
    "treatments": 20,
    "bio":
        "Dr. Esam Rehawe is a compassionate and experienced oncologist dedicated to the diagnosis and treatment of cancer.",
    "qualifications": [
      "Doctor of Medicine (MD) with a specialization in Oncology",
      "Board Certified in Medical Oncology",
      "Extensive experience in chemotherapy,",
      "Strong background in cancer research and evidence-based practice",
      "Excellent skills in patient communication, care planning, and follow-up",
    ],
  },
];
