var completedAppointmentsDetails = {
  1: {
    "medications": [
      {
        "id": 1,
        "name": "Hydrocortisone",
        "type": "cream",
        "dosage": "1%",
        "frequency": "twice daily",
        "duration": "7 days",
        "note": "Apply thinly to affected area",
      },
      {
        "id": 2,
        "name": "Cetirizine",
        "type": "tablet",
        "dosage": "10mg",
        "frequency": "once daily",
        "duration": "14 days",
        "note": "For itching or allergic reactions",
      },
      {
        "id": 3,
        "name": "Clindamycin",
        "type": "gel",
        "dosage": "1%",
        "frequency": "once daily",
        "duration": "4 weeks",
        "note": "Use on acne-prone areas",
      },
    ],
    "lab_tests": [
      {"id": 1, "name": "Skin Scraping for Fungal Test"},
      {"id": 2, "name": "Allergy Patch Test"},
      {"id": 3, "name": "Complete Blood Count (CBC)"},
    ],
    "surgeries": [
      {"id": 1, "name": "Skin Biopsy"},
      {"id": 2, "name": "Mole Removal"},
      {"id": 3, "name": "Cyst Excision"},
    ],
    "advices": [
      {"id": 1, "advice": "Avoid direct sun exposure; use sunscreen."},
      {"id": 2, "advice": "Keep skin clean and moisturized."},
      {"id": 3, "advice": "Avoid scratching affected areas."},
      {"id": 4, "advice": "Use prescribed products only on affected areas."},
    ],
    "is_prescription_viewed": false,
  },
  2: {
    "medications": [
      {
        "id": 1,
        "name": "Gabapentin",
        "type": "capsules",
        "dosage": "300mg",
        "frequency": "3 times daily",
        "duration": "14 days",
        "note": "May cause dizziness or drowsiness",
      },
      {
        "id": 2,
        "name": "Levetiracetam",
        "type": "tablets",
        "dosage": "500mg",
        "frequency": "twice daily",
        "duration": "30 days",
        "note": "Monitor mood and behavior changes",
      },
      {
        "id": 3,
        "name": "Amitriptyline",
        "type": "tablets",
        "dosage": "25mg",
        "frequency": "once at bedtime",
        "duration": "30 days",
        "note": "Helps with nerve pain and sleep",
      },
      {
        "id": 4,
        "name": "Topiramate",
        "type": "tablets",
        "dosage": "50mg",
        "frequency": "twice daily",
        "duration": "30 days",
        "note": "Used for migraine prevention",
      },
      {
        "id": 5,
        "name": "Duloxetine",
        "type": "capsules",
        "dosage": "60mg",
        "frequency": "once daily",
        "duration": "30 days",
        "note": "May help with neuropathic pain",
      },
      {
        "id": 6,
        "name": "Clonazepam",
        "type": "tablets",
        "dosage": "0.5mg",
        "frequency": "twice daily",
        "duration": "10 days",
        "note": "Short-term use for seizure control",
      },
    ],
    "lab_tests": [
      {"id": 1, "name": "Electroencephalogram (EEG)"},
      {"id": 2, "name": "Magnetic Resonance Imaging (MRI) Brain"},
      {"id": 3, "name": "Computed Tomography (CT) Brain"},
      {"id": 4, "name": "Lumbar Puncture (CSF Analysis)"},
      {"id": 5, "name": "Vitamin B12 Level"},
      {"id": 6, "name": "Thyroid Function Test (TFT)"},
      {"id": 7, "name": "Electromyography (EMG)"},
      {"id": 8, "name": "Nerve Conduction Study (NCS)"},
      {"id": 9, "name": "Autoimmune Encephalitis Panel"},
      {"id": 10, "name": "Toxicology Screen"},
    ],
    "surgeries": [
      {"id": 1, "name": "Craniotomy for Tumor Removal"},
      {"id": 2, "name": "Deep Brain Stimulation (DBS)"},
      {"id": 3, "name": "Vagus Nerve Stimulation (VNS)"},
      {"id": 4, "name": "Spinal Cord Stimulator Implantation"},
      {"id": 5, "name": "Aneurysm Clipping"},
      {"id": 6, "name": "Endovascular Coiling"},
      {"id": 7, "name": "Epilepsy Surgery"},
      {"id": 8, "name": "Carotid Endarterectomy"},
    ],
    "advices": [
      {"id": 1, "advice": "Get 7–9 hours of sleep each night."},
      {
        "id": 2,
        "advice":
            "Avoid triggers such as bright lights and loud noises if prone to migraines.",
      },
      {"id": 3, "advice": "Take your medications regularly and on time."},
      {"id": 4, "advice": "Avoid alcohol and recreational drugs."},
      {
        "id": 5,
        "advice":
            "Practice stress-reduction techniques such as meditation or yoga.",
      },
      {
        "id": 6,
        "advice":
            "Report any new or worsening symptoms to your neurologist promptly.",
      },
      {
        "id": 7,
        "advice":
            "Maintain a healthy diet rich in fruits, vegetables, and omega-3s.",
      },
      {"id": 8, "advice": "Stay hydrated and avoid excessive caffeine."},
      {
        "id": 9,
        "advice": "Use seizure precautions if diagnosed with epilepsy.",
      },
      {
        "id": 10,
        "advice":
            "Attend regular follow-up appointments for monitoring and adjustments.",
      },
    ],
    "is_prescription_viewed": false,
  },
  3: {
    "medications": [
      {
        "id": 1,
        "name": "Amoxicillin",
        "type": "syrup",
        "dosage": "5ml",
        "frequency": "3 times daily",
        "duration": "7 days",
        "note": "complete full course",
      },
      {
        "id": 2,
        "name": "Ibuprofen",
        "type": "syrup",
        "dosage": "5ml",
        "frequency": "every 6–8 hours",
        "duration": "5 days",
        "note": "Give with food",
      },
      {
        "id": 3,
        "name": "Paracetamol",
        "type": "syrup",
        "dosage": "5ml",
        "frequency": "every 4–6 hours",
        "duration": "3 days",
        "note": "4 doses per day",
      },
      {
        "id": 4,
        "name": "Salbutamol",
        "type": "inhaler",
        "dosage": "100mcg/puff",
        "frequency": "as needed",
        "duration": "as prescribed",
        "note": "Use with spacer",
      },
      {
        "id": 5,
        "name": "Cetirizine",
        "type": "syrup",
        "dosage": "5mg/5ml",
        "frequency": "once daily",
        "duration": "10 days",
        "note": "Used for allergies or rhinitis",
      },
    ],
    "lab_tests": [
      {"id": 1, "name": "Complete Blood Count (CBC)"},
      {"id": 2, "name": "Stool Examination"},
      {"id": 3, "name": "Urinalysis"},
      {"id": 4, "name": "Throat Culture"},
      {"id": 5, "name": "Blood Culture"},
      {"id": 6, "name": "Serum Electrolytes"},
      {"id": 7, "name": "Liver Function Tests (LFTs)"},
      {"id": 8, "name": "Renal Function Tests (RFTs)"},
      {"id": 9, "name": "CRP (C-Reactive Protein)"},
      {"id": 10, "name": "Rapid Antigen Test for Strep"},
    ],
    "surgeries": [
      {"id": 1, "name": "Tonsillectomy"},
      {"id": 2, "name": "Adenoidectomy"},
      {"id": 3, "name": "Appendectomy"},
      {"id": 4, "name": "Hernia Repair"},
      {"id": 5, "name": "Circumcision"},
      {"id": 6, "name": "Hydrocele Surgery"},
      {"id": 7, "name": "Ear Tube Placement (Myringotomy)"},
      {"id": 8, "name": "Cleft Lip Repair"},
    ],
    "advices": [
      {"id": 1, "advice": "Ensure your child stays hydrated."},
      {
        "id": 2,
        "advice":
            "Complete all prescribed medications even if the child feels better.",
      },
      {"id": 3, "advice": "Keep vaccinations up to date."},
      {"id": 4, "advice": "Wash hands frequently to prevent infection."},
      {
        "id": 5,
        "advice": "Monitor temperature regularly if the child has a fever.",
      },
      {
        "id": 6,
        "advice": "Provide a balanced diet with fruits and vegetables.",
      },
      {"id": 7, "advice": "Avoid sending the child to school if sick."},
      {
        "id": 8,
        "advice": "Use medications only as directed by your pediatrician.",
      },
      {
        "id": 9,
        "advice":
            "Keep harmful substances and small objects out of children's reach.",
      },
      {"id": 10, "advice": "Follow up as scheduled for reassessment."},
    ],
    "is_prescription_viewed": true,
  },
};
