var myBillsDetails = {
  6: {
    "Id": "# 6",
    "Status": "Unpaid",
    "Payment Date": "----",
    "Payment Time": "----",
    "Payment Method": "Cash",
    "Follow-Up Price": "20000.0 SYP",
    "Medical Report Price": "6000.0 SYP",
    "Total Price": "26000.0 SYP",
  },
  5: {
    "Id": "# 5",
    "Status": "Unpaid",
    "Payment Date": "----",
    "Payment Time": "----",
    "Payment Method": "Cash",
    "Check-Up Price": "25000.0 SYP",
    "Dental Cleaning Price": "50000.0 SYP",
    "Tooth Extraction Price": "30000.0 SYP",
    "Dental Crown Price": "20000.0 SYP",
    "Total Price": "125000.0 SYP",
  },
  4: {
    "Id": "# 4",
    "Status": "Unpaid",
    "Payment Date": "----",
    "Payment Time": "----",
    "Payment Method": "Points",
    "Offer Price": "75.0 Points",
  },
  3: {
    "Id": "# 3",
    "Status": "Paid",
    "Payment Date": "2 July 2025",
    "Payment Time": "12:30 PM",
    "Payment Method": "Points",
    "Offer Price": "50.0 Points",
  },
  2: {
    "Id": "#2",
    "Status": "Paid",
    "Payment Date": "24 June 2025",
    "Payment Time": "11:30 AM",
    "Payment Method": "Cash",
    "Check-Up Price": "50000.0 SYP",
    "Medical Report Price": "6000.0 SYP",
    "Vaccination Price": "20000.0 SYP",
    "Pediatric ECG": "30000.0 SYP",
    "Total Price": "106000.0 SYP",
  },
  1: {
    "Id": "#1",
    "Status": "Paid",
    "Payment Date": "15 April 2025",
    "Payment Time": "10:45 AM",
    "Payment Method": "Cash",
    "Follow-Up Price": "20000.0 SYP",
    "Medical Report Price": "6000.0 SYP",
    "Total Price": "26000.0 SYP",
  },
};
