var myMorningDepartmentsDoctors = {
  1: [
    {
      "id": 1,
      "name": "Alice Heart",
      "image": "assets/images/doctor1.png",
      "shift": "Morning",
      "treatments": 320,
      "experience": 12,
      "rate": 4.8,
    },
    {
      "id": 3,
      "name": "Mia Valve",
      "image": "assets/images/doctor3.png",
      "shift": "Morning",
      "treatments": 280,
      "experience": 8,
      "rate": 4.5,
    },
    {
      "id": 5,
      "name": "Clara Beat",
      "image": "assets/images/doctor5.png",
      "shift": "Morning",
      "treatments": 500,
      "experience": 15,
      "rate": 4.9,
    },
  ],
  2: [
    {
      "id": 7,
      "name": "Liam Derma",
      "image": "assets/images/doctor7.png",
      "shift": "Morning",
      "treatments": 340,
      "experience": 10,
      "rate": 4.6,
    },
    {
      "id": 9,
      "name": "Ryan Pore",
      "image": "assets/images/doctor9.png",
      "shift": "Morning",
      "treatments": 300,
      "experience": 11,
      "rate": 4.7,
    },
  ],
  3: [
    {
      "id": 11,
      "name": "Adam Brain",
      "image": "assets/images/doctor11.png",
      "shift": "Morning",
      "treatments": 410,
      "experience": 14,
      "rate": 4.8,
    },
    {
      "id": 13,
      "name": "Leo Cortex",
      "image": "assets/images/doctor13.png",
      "shift": "Morning",
      "treatments": 330,
      "experience": 11,
      "rate": 4.5,
    },
    {
      "id": 15,
      "name": "Max Synapse",
      "image": "assets/images/doctor15.png",
      "shift": "Morning",
      "treatments": 400,
      "experience": 13,
      "rate": 4.9,
    },
  ],
  4: [
    {
      "id": 17,
      "name": "Emma Joint",
      "image": "assets/images/doctor17.png",
      "shift": "Morning",
      "treatments": 310,
      "experience": 10,
      "rate": 4.6,
    },
    {
      "id": 19,
      "name": "Ava Limb",
      "image": "assets/images/doctor19.png",
      "shift": "Morning",
      "treatments": 290,
      "experience": 8,
      "rate": 4.4,
    },
  ],
};

var myAfternoonDepartmentsDoctors = {
  1: [
    {
      "id": 2,
      "name": "Sam Pulse",
      "image": "assets/images/doctor2.png",
      "shift": "Afternoon",
      "treatments": 410,
      "experience": 10,
      "rate": 4.7,
    },
    {
      "id": 4,
      "name": "Jack Rhythm",
      "image": "assets/images/doctor4.png",
      "shift": "Afternoon",
      "treatments": 300,
      "experience": 9,
      "rate": 4.6,
    },
  ],
  2: [
    {
      "id": 6,
      "name": "Nina Skin",
      "image": "assets/images/doctor6.png",
      "shift": "Afternoon",
      "treatments": 200,
      "experience": 7,
      "rate": 4.4,
    },
    {
      "id": 8,
      "name": "Zoe Peel",
      "image": "assets/images/doctor8.png",
      "shift": "Afternoon",
      "treatments": 260,
      "experience": 6,
      "rate": 4.3,
    },
    {
      "id": 10,
      "name": "Ella Spot",
      "image": "assets/images/doctor10.png",
      "shift": "Afternoon",
      "treatments": 210,
      "experience": 5,
      "rate": 4.2,
    },
  ],
  3: [
    {
      "id": 12,
      "name": "Kate Nerve",
      "image": "assets/images/doctor12.png",
      "shift": "Afternoon",
      "treatments": 370,
      "experience": 12,
      "rate": 4.6,
    },
    {
      "id": 14,
      "name": "Ruby Mind",
      "image": "assets/images/doctor14.png",
      "shift": "Afternoon",
      "treatments": 350,
      "experience": 10,
      "rate": 4.7,
    },
  ],
  4: [
    {
      "id": 16,
      "name": "Mark Bone",
      "image": "assets/images/doctor16.png",
      "shift": "Afternoon",
      "treatments": 250,
      "experience": 9,
      "rate": 4.5,
    },
    {
      "id": 18,
      "name": "Henry Spine",
      "image": "assets/images/doctor18.png",
      "shift": "Afternoon",
      "treatments": 270,
      "experience": 7,
      "rate": 4.3,
    },
    {
      "id": 20,
      "name": "John Cast",
      "image": "assets/images/doctor20.png",
      "shift": "Afternoon",
      "treatments": 230,
      "experience": 6,
      "rate": 4.2,
    },
  ],
};
