// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpO3XfQlUTMU7A9OZ6MTF_zz456Rls65c',
    appId: '1:320019208259:android:b3c66eb8367180c7961cf6',
    messagingSenderId: '320019208259',
    projectId: 'push-notifications-62aa8',
    storageBucket: 'push-notifications-62aa8.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm4F8ENxc764-VyF1dBzV1g3nZXFAj_ME',
    appId: '1:320019208259:web:106aa9aaad85da3e961cf6',
    messagingSenderId: '320019208259',
    projectId: 'push-notifications-62aa8',
    authDomain: 'push-notifications-62aa8.firebaseapp.com',
    storageBucket: 'push-notifications-62aa8.firebasestorage.app',
    measurementId: 'G-HJ7SJF559H',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD31_jbqDsdMczJIGqKb4thR2l8yH1xE-E',
    appId: '1:320019208259:ios:c72702b347479131961cf6',
    messagingSenderId: '320019208259',
    projectId: 'push-notifications-62aa8',
    storageBucket: 'push-notifications-62aa8.firebasestorage.app',
    iosBundleId: 'com.example.clinicApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD31_jbqDsdMczJIGqKb4thR2l8yH1xE-E',
    appId: '1:320019208259:ios:c72702b347479131961cf6',
    messagingSenderId: '320019208259',
    projectId: 'push-notifications-62aa8',
    storageBucket: 'push-notifications-62aa8.firebasestorage.app',
    iosBundleId: 'com.example.clinicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm4F8ENxc764-VyF1dBzV1g3nZXFAj_ME',
    appId: '1:320019208259:web:4f6b6b462ed50414961cf6',
    messagingSenderId: '320019208259',
    projectId: 'push-notifications-62aa8',
    authDomain: 'push-notifications-62aa8.firebaseapp.com',
    storageBucket: 'push-notifications-62aa8.firebasestorage.app',
    measurementId: 'G-MQSDHSDSSR',
  );

}