// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYJi4v_hIt_plwnOMCVnz1XEUFRe6EkFA',
    appId: '1:99133053624:web:a9b3b411c9578641c8f24d',
    messagingSenderId: '99133053624',
    projectId: 'healthcore-bdd68',
    authDomain: 'healthcore-bdd68.firebaseapp.com',
    storageBucket: 'healthcore-bdd68.firebasestorage.app',
    measurementId: 'G-8YDBMJ33HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3mXYTBK8uMRZwOFi6ryxBge5ncPP3EM',
    appId: '1:99133053624:android:272ee53daee6c165c8f24d',
    messagingSenderId: '99133053624',
    projectId: 'healthcore-bdd68',
    storageBucket: 'healthcore-bdd68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEbLztZAzSdYmchDzq7r05ePT0VArTEqg',
    appId: '1:99133053624:ios:8fbf753e0b3331e2c8f24d',
    messagingSenderId: '99133053624',
    projectId: 'healthcore-bdd68',
    storageBucket: 'healthcore-bdd68.firebasestorage.app',
    iosBundleId: 'com.example.clinicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEbLztZAzSdYmchDzq7r05ePT0VArTEqg',
    appId: '1:99133053624:ios:8fbf753e0b3331e2c8f24d',
    messagingSenderId: '99133053624',
    projectId: 'healthcore-bdd68',
    storageBucket: 'healthcore-bdd68.firebasestorage.app',
    iosBundleId: 'com.example.clinicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYJi4v_hIt_plwnOMCVnz1XEUFRe6EkFA',
    appId: '1:99133053624:web:1bc5c7cd9c111b92c8f24d',
    messagingSenderId: '99133053624',
    projectId: 'healthcore-bdd68',
    authDomain: 'healthcore-bdd68.firebaseapp.com',
    storageBucket: 'healthcore-bdd68.firebasestorage.app',
    measurementId: 'G-7W1CDYYQZK',
  );
}
