final myPendingAppointments = [
  {
    "id": 1,
    "shift": "morning",
    "status": "Pending",
    "doctor_name": "Layla Hassan",
    "doctor_image": "assets/images/doctor1.png",
    "department": "Cardiology",
    "date_time": "2025-08-12T10:30:00Z",
    "request_type_id": 1,
    "with_medical_report": true,
  },
  {
    "id": 2,
    "shift": "morning",
    "status": "Pending",
    "doctor_name": "Fares Al Midany",
    "doctor_image": "assets/images/doctor2.png",
    "department": "Neurology",
    "date_time": "2025-08-13T12:30:00Z",
    "request_type_id": 2,
    "with_medical_report": false,
  },
  {
    "id": 3,
    "shift": "afternoon",
    "status": "Pending",
    "doctor_name": "Rand Skaf",
    "doctor_image": "assets/images/doctor4.png",
    "department": "Pediatrics",
    "date_time": "2025-08-14T15:00:00Z",
    "request_type_id": 2,
    "with_medical_report": true,
  },
];

final myCompletedAppointments = [
  {
    "id": 1,
    "shift": "morning",
    "status": "Completed",
    "doctor_name": "Maya Al Qassem",
    "doctor_image": "assets/images/doctor6.png",
    "department": "Dermatology",
    "date_time": "2025-05-10T10:30:00Z",
    "request_type_id": 1,
    "with_medical_report": true,
  },
  {
    "id": 2,
    "shift": "morning",
    "status": "Completed",
    "doctor_name": "Fares Al Midany",
    "doctor_image": "assets/images/doctor2.png",
    "department": "Neurology",
    "date_time": "2025-05-05T10:00:00Z",
    "request_type_id": 1,
    "with_medical_report": true,
  },
  {
    "id": 3,
    "shift": "afternoon",
    "status": "Completed",
    "doctor_name": "Rand Skaf",
    "doctor_image": "assets/images/doctor4.png",
    "department": "Pediatrics",
    "date_time": "2025-05-01T17:30:00Z",
    "request_type_id": 1,
    "with_medical_report": false,
  },
];
